//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 系统错误,请重新录入数据 的本地化字符串。
        /// </summary>
        internal static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据为空，请确认后重试 的本地化字符串。
        /// </summary>
        internal static string alertksj {
            get {
                return ResourceManager.GetString("alertksj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资料不存在,请检查部番是否输入正确 的本地化字符串。
        /// </summary>
        internal static string alertNodata {
            get {
                return ResourceManager.GetString("alertNodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入日期错误 的本地化字符串。
        /// </summary>
        internal static string alertsjcw {
            get {
                return ResourceManager.GetString("alertsjcw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请完整填写资料 的本地化字符串。
        /// </summary>
        internal static string alerttx {
            get {
                return ResourceManager.GetString("alerttx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓位点中无数据,无需启动盘点 的本地化字符串。
        /// </summary>
        internal static string alertWsj {
            get {
                return ResourceManager.GetString("alertWsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓位点盘库已存在，无需重新启动 的本地化字符串。
        /// </summary>
        internal static string alertWxqd {
            get {
                return ResourceManager.GetString("alertWxqd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件必须为Excel 的本地化字符串。
        /// </summary>
        internal static string alertxzexcel {
            get {
                return ResourceManager.GetString("alertxzexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择上传文件 的本地化字符串。
        /// </summary>
        internal static string alertxzwj {
            get {
                return ResourceManager.GetString("alertxzwj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无需再次确认 的本地化字符串。
        /// </summary>
        internal static string alterDoubbleConfirm {
            get {
                return ResourceManager.GetString("alterDoubbleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        internal static string alterfiald {
            get {
                return ResourceManager.GetString("alterfiald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string alterOk {
            get {
                return ResourceManager.GetString("alterOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无需反审 的本地化字符串。
        /// </summary>
        internal static string alterReConfrim {
            get {
                return ResourceManager.GetString("alterReConfrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有选择任何行 的本地化字符串。
        /// </summary>
        internal static string alterwxz {
            get {
                return ResourceManager.GetString("alterwxz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string bc {
            get {
                return ResourceManager.GetString("bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部番 的本地化字符串。
        /// </summary>
        internal static string bf {
            get {
                return ResourceManager.GetString("bf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string bh {
            get {
                return ResourceManager.GetString("bh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备货指示号 的本地化字符串。
        /// </summary>
        internal static string bhzsh {
            get {
                return ResourceManager.GetString("bhzsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备货指示号数据明细 的本地化字符串。
        /// </summary>
        internal static string bhzshsjmx {
            get {
                return ResourceManager.GetString("bhzshsjmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备料指示号 的本地化字符串。
        /// </summary>
        internal static string blzsh {
            get {
                return ResourceManager.GetString("blzsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品名 的本地化字符串。
        /// </summary>
        internal static string bpmc {
            get {
                return ResourceManager.GetString("bpmc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部品名称 的本地化字符串。
        /// </summary>
        internal static string bpmc1 {
            get {
                return ResourceManager.GetString("bpmc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部品重量 的本地化字符串。
        /// </summary>
        internal static string bpzl {
            get {
                return ResourceManager.GetString("bpzl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string bz {
            get {
                return ResourceManager.GetString("bz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 别纸 的本地化字符串。
        /// </summary>
        internal static string bz1 {
            get {
                return ResourceManager.GetString("bz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 材质表示 的本地化字符串。
        /// </summary>
        internal static string cabs {
            get {
                return ResourceManager.GetString("cabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string caozuo {
            get {
                return ResourceManager.GetString("caozuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测定具 的本地化字符串。
        /// </summary>
        internal static string cdj {
            get {
                return ResourceManager.GetString("cdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        internal static string cjr {
            get {
                return ResourceManager.GetString("cjr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日期 的本地化字符串。
        /// </summary>
        internal static string cjrq {
            get {
                return ResourceManager.GetString("cjrq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        internal static string ck {
            get {
                return ResourceManager.GetString("ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓位点 的本地化字符串。
        /// </summary>
        internal static string clck {
            get {
                return ResourceManager.GetString("clck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 材料仓库 的本地化字符串。
        /// </summary>
        internal static string clck1 {
            get {
                return ResourceManager.GetString("clck1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 材料管理 的本地化字符串。
        /// </summary>
        internal static string clgl {
            get {
                return ResourceManager.GetString("clgl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 材料供应商色番 的本地化字符串。
        /// </summary>
        internal static string clgyssf {
            get {
                return ResourceManager.GetString("clgyssf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 材料价格修改详细 的本地化字符串。
        /// </summary>
        internal static string cljgxgxx {
            get {
                return ResourceManager.GetString("cljgxgxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理区域 的本地化字符串。
        /// </summary>
        internal static string clqy {
            get {
                return ResourceManager.GetString("clqy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量项目 的本地化字符串。
        /// </summary>
        internal static string clxm {
            get {
                return ResourceManager.GetString("clxm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承认 的本地化字符串。
        /// </summary>
        internal static string cr {
            get {
                return ResourceManager.GetString("cr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承认图 的本地化字符串。
        /// </summary>
        internal static string crt {
            get {
                return ResourceManager.GetString("crt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城市 的本地化字符串。
        /// </summary>
        internal static string cs {
            get {
                return ResourceManager.GetString("cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成型 的本地化字符串。
        /// </summary>
        internal static string cx {
            get {
                return ResourceManager.GetString("cx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 差异 的本地化字符串。
        /// </summary>
        internal static string cy {
            get {
                return ResourceManager.GetString("cy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 差异汇总 的本地化字符串。
        /// </summary>
        internal static string cyhz {
            get {
                return ResourceManager.GetString("cyhz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 材质 的本地化字符串。
        /// </summary>
        internal static string cz {
            get {
                return ResourceManager.GetString("cz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传真 的本地化字符串。
        /// </summary>
        internal static string cz1 {
            get {
                return ResourceManager.GetString("cz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作人员 的本地化字符串。
        /// </summary>
        internal static string czry {
            get {
                return ResourceManager.GetString("czry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string dc {
            get {
                return ResourceManager.GetString("dc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出盘点票 的本地化字符串。
        /// </summary>
        internal static string dcpdp {
            get {
                return ResourceManager.GetString("dcpdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 担当 的本地化字符串。
        /// </summary>
        internal static string dd {
            get {
                return ResourceManager.GetString("dd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string dh {
            get {
                return ResourceManager.GetString("dh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单价 的本地化字符串。
        /// </summary>
        internal static string dj {
            get {
                return ResourceManager.GetString("dj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对照 的本地化字符串。
        /// </summary>
        internal static string duizhao {
            get {
                return ResourceManager.GetString("duizhao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        internal static string dw {
            get {
                return ResourceManager.GetString("dw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        internal static string dy {
            get {
                return ResourceManager.GetString("dy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印盘点票 的本地化字符串。
        /// </summary>
        internal static string dypdp {
            get {
                return ResourceManager.GetString("dypdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string dz {
            get {
                return ResourceManager.GetString("dz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粉碎完成 的本地化字符串。
        /// </summary>
        internal static string fcwc {
            get {
                return ResourceManager.GetString("fcwc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string fh {
            get {
                return ResourceManager.GetString("fh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回上一页 的本地化字符串。
        /// </summary>
        internal static string fhsyy {
            get {
                return ResourceManager.GetString("fhsyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反审 的本地化字符串。
        /// </summary>
        internal static string fs {
            get {
                return ResourceManager.GetString("fs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反审 的本地化字符串。
        /// </summary>
        internal static string fs1 {
            get {
                return ResourceManager.GetString("fs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反审当前 的本地化字符串。
        /// </summary>
        internal static string fsdq {
            get {
                return ResourceManager.GetString("fsdq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反审当前 的本地化字符串。
        /// </summary>
        internal static string fsdq1 {
            get {
                return ResourceManager.GetString("fsdq1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粉碎料比例 的本地化字符串。
        /// </summary>
        internal static string fslbl {
            get {
                return ResourceManager.GetString("fslbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负数项 的本地化字符串。
        /// </summary>
        internal static string fsx {
            get {
                return ResourceManager.GetString("fsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发行 的本地化字符串。
        /// </summary>
        internal static string fx {
            get {
                return ResourceManager.GetString("fx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程内检查规格书 的本地化字符串。
        /// </summary>
        internal static string gcnjcggs {
            get {
                return ResourceManager.GetString("gcnjcggs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程内检查规格书列表 的本地化字符串。
        /// </summary>
        internal static string gcnjcggslb {
            get {
                return ResourceManager.GetString("gcnjcggslb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公差起 的本地化字符串。
        /// </summary>
        internal static string gcq {
            get {
                return ResourceManager.GetString("gcq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公差止 的本地化字符串。
        /// </summary>
        internal static string gcz {
            get {
                return ResourceManager.GetString("gcz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改订内容 的本地化字符串。
        /// </summary>
        internal static string gdnr {
            get {
                return ResourceManager.GetString("gdnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改订日期 的本地化字符串。
        /// </summary>
        internal static string gdrq {
            get {
                return ResourceManager.GetString("gdrq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规格 的本地化字符串。
        /// </summary>
        internal static string gg {
            get {
                return ResourceManager.GetString("gg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商管理 的本地化字符串。
        /// </summary>
        internal static string ggsgl {
            get {
                return ResourceManager.GetString("ggsgl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买商 的本地化字符串。
        /// </summary>
        internal static string gms {
            get {
                return ResourceManager.GetString("gms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        internal static string gx {
            get {
                return ResourceManager.GetString("gx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商 的本地化字符串。
        /// </summary>
        internal static string gys {
            get {
                return ResourceManager.GetString("gys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商编号 的本地化字符串。
        /// </summary>
        internal static string gysbh {
            get {
                return ResourceManager.GetString("gysbh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商简称 的本地化字符串。
        /// </summary>
        internal static string gysjc {
            get {
                return ResourceManager.GetString("gysjc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商名 的本地化字符串。
        /// </summary>
        internal static string gysm {
            get {
                return ResourceManager.GetString("gysm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商信息维护 的本地化字符串。
        /// </summary>
        internal static string gysxxwh {
            get {
                return ResourceManager.GetString("gysxxwh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 干燥时间 的本地化字符串。
        /// </summary>
        internal static string gzsj {
            get {
                return ResourceManager.GetString("gzsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 干燥温度 的本地化字符串。
        /// </summary>
        internal static string gzwd {
            get {
                return ResourceManager.GetString("gzwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复 的本地化字符串。
        /// </summary>
        internal static string hf {
            get {
                return ResourceManager.GetString("hf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计 的本地化字符串。
        /// </summary>
        internal static string hj {
            get {
                return ResourceManager.GetString("hj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货位号 的本地化字符串。
        /// </summary>
        internal static string hwh {
            get {
                return ResourceManager.GetString("hwh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否成产厂家 的本地化字符串。
        /// </summary>
        internal static string issccj {
            get {
                return ResourceManager.GetString("issccj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 见本标准样本 的本地化字符串。
        /// </summary>
        internal static string jbbzyb {
            get {
                return ResourceManager.GetString("jbbzyb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 见本限度 的本地化字符串。
        /// </summary>
        internal static string jbxd {
            get {
                return ResourceManager.GetString("jbxd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查频度 的本地化字符串。
        /// </summary>
        internal static string jcpd {
            get {
                return ResourceManager.GetString("jcpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查项目 的本地化字符串。
        /// </summary>
        internal static string jcxm {
            get {
                return ResourceManager.GetString("jcxm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额 的本地化字符串。
        /// </summary>
        internal static string je {
            get {
                return ResourceManager.GetString("je", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记号 的本地化字符串。
        /// </summary>
        internal static string jh {
            get {
                return ResourceManager.GetString("jh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交货上传 的本地化字符串。
        /// </summary>
        internal static string jhsc {
            get {
                return ResourceManager.GetString("jhsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终止时间 的本地化字符串。
        /// </summary>
        internal static string jssj {
            get {
                return ResourceManager.GetString("jssj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机型 的本地化字符串。
        /// </summary>
        internal static string jx {
            get {
                return ResourceManager.GetString("jx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机种 的本地化字符串。
        /// </summary>
        internal static string jz {
            get {
                return ResourceManager.GetString("jz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户 的本地化字符串。
        /// </summary>
        internal static string kh {
            get {
                return ResourceManager.GetString("kh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户 的本地化字符串。
        /// </summary>
        internal static string kh1 {
            get {
                return ResourceManager.GetString("kh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始粉碎 的本地化字符串。
        /// </summary>
        internal static string ksfc {
            get {
                return ResourceManager.GetString("ksfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始时间 的本地化字符串。
        /// </summary>
        internal static string kssj {
            get {
                return ResourceManager.GetString("kssj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人 的本地化字符串。
        /// </summary>
        internal static string lxr {
            get {
                return ResourceManager.GetString("lxr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string mc {
            get {
                return ResourceManager.GetString("mc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模具编号 的本地化字符串。
        /// </summary>
        internal static string mjbh {
            get {
                return ResourceManager.GetString("mjbh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次号 的本地化字符串。
        /// </summary>
        internal static string pch {
            get {
                return ResourceManager.GetString("pch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点表号 的本地化字符串。
        /// </summary>
        internal static string pdbh {
            get {
                return ResourceManager.GetString("pdbh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点表号 的本地化字符串。
        /// </summary>
        internal static string pdbh1 {
            get {
                return ResourceManager.GetString("pdbh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点表录入 的本地化字符串。
        /// </summary>
        internal static string pdblr {
            get {
                return ResourceManager.GetString("pdblr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点表确认(审核) 的本地化字符串。
        /// </summary>
        internal static string pdbqr {
            get {
                return ResourceManager.GetString("pdbqr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点表确认（审核） 的本地化字符串。
        /// </summary>
        internal static string pdbqr1 {
            get {
                return ResourceManager.GetString("pdbqr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点表审核 的本地化字符串。
        /// </summary>
        internal static string pdbsh {
            get {
                return ResourceManager.GetString("pdbsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点表制单日期 的本地化字符串。
        /// </summary>
        internal static string pdbzdrq {
            get {
                return ResourceManager.GetString("pdbzdrq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点单号 的本地化字符串。
        /// </summary>
        internal static string pddh {
            get {
                return ResourceManager.GetString("pddh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点单号 的本地化字符串。
        /// </summary>
        internal static string pddh1 {
            get {
                return ResourceManager.GetString("pddh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点模式 的本地化字符串。
        /// </summary>
        internal static string pdms {
            get {
                return ResourceManager.GetString("pdms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点日期 的本地化字符串。
        /// </summary>
        internal static string pdrq {
            get {
                return ResourceManager.GetString("pdrq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点日期 的本地化字符串。
        /// </summary>
        internal static string pdrq1 {
            get {
                return ResourceManager.GetString("pdrq1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点数量 的本地化字符串。
        /// </summary>
        internal static string pdsl {
            get {
                return ResourceManager.GetString("pdsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 盘点商品 的本地化字符串。
        /// </summary>
        internal static string pdsp {
            get {
                return ResourceManager.GetString("pdsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量上传 的本地化字符串。
        /// </summary>
        internal static string plsc {
            get {
                return ResourceManager.GetString("plsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品名 的本地化字符串。
        /// </summary>
        internal static string pm {
            get {
                return ResourceManager.GetString("pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string qd {
            get {
                return ResourceManager.GetString("qd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动盘点 的本地化字符串。
        /// </summary>
        internal static string qdpd {
            get {
                return ResourceManager.GetString("qdpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string qr {
            get {
                return ResourceManager.GetString("qr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string qr1 {
            get {
                return ResourceManager.GetString("qr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认当前 的本地化字符串。
        /// </summary>
        internal static string qrdq {
            get {
                return ResourceManager.GetString("qrdq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认当期 的本地化字符串。
        /// </summary>
        internal static string qrdq1 {
            get {
                return ResourceManager.GetString("qrdq1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认审核 的本地化字符串。
        /// </summary>
        internal static string qrsh {
            get {
                return ResourceManager.GetString("qrsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取数 的本地化字符串。
        /// </summary>
        internal static string qs {
            get {
                return ResourceManager.GetString("qs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入供应商名 的本地化字符串。
        /// </summary>
        internal static string qsrgysm {
            get {
                return ResourceManager.GetString("qsrgysm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string qx {
            get {
                return ResourceManager.GetString("qx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string qxz {
            get {
                return ResourceManager.GetString("qxz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域 的本地化字符串。
        /// </summary>
        internal static string qy {
            get {
                return ResourceManager.GetString("qy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按染色料计算 的本地化字符串。
        /// </summary>
        internal static string rsl {
            get {
                return ResourceManager.GetString("rsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 认证 的本地化字符串。
        /// </summary>
        internal static string rz {
            get {
                return ResourceManager.GetString("rz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string sc {
            get {
                return ResourceManager.GetString("sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string sc1 {
            get {
                return ResourceManager.GetString("sc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产厂家 的本地化字符串。
        /// </summary>
        internal static string sccj {
            get {
                return ResourceManager.GetString("sccj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除行 的本地化字符串。
        /// </summary>
        internal static string sch {
            get {
                return ResourceManager.GetString("sch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色番 的本地化字符串。
        /// </summary>
        internal static string sf {
            get {
                return ResourceManager.GetString("sf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色粉购买商 的本地化字符串。
        /// </summary>
        internal static string sfgms {
            get {
                return ResourceManager.GetString("sfgms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否确认该盘点表? 的本地化字符串。
        /// </summary>
        internal static string sfscpdb {
            get {
                return ResourceManager.GetString("sfscpdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色粉型号 的本地化字符串。
        /// </summary>
        internal static string sfxh {
            get {
                return ResourceManager.GetString("sfxh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        internal static string sh {
            get {
                return ResourceManager.GetString("sh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        internal static string sh1 {
            get {
                return ResourceManager.GetString("sh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货日期 的本地化字符串。
        /// </summary>
        internal static string shrq {
            get {
                return ResourceManager.GetString("shrq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核意见 的本地化字符串。
        /// </summary>
        internal static string shyj {
            get {
                return ResourceManager.GetString("shyj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据管理 的本地化字符串。
        /// </summary>
        internal static string sjgl {
            get {
                return ResourceManager.GetString("sjgl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据上传 的本地化字符串。
        /// </summary>
        internal static string sjsc {
            get {
                return ResourceManager.GetString("sjsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水口重量 的本地化字符串。
        /// </summary>
        internal static string skzl {
            get {
                return ResourceManager.GetString("skzl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品 的本地化字符串。
        /// </summary>
        internal static string sp {
            get {
                return ResourceManager.GetString("sp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品档案 的本地化字符串。
        /// </summary>
        internal static string spda {
            get {
                return ResourceManager.GetString("spda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品属性 的本地化字符串。
        /// </summary>
        internal static string spsx {
            get {
                return ResourceManager.GetString("spsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收索 的本地化字符串。
        /// </summary>
        internal static string ss {
            get {
                return ResourceManager.GetString("ss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时库存 的本地化字符串。
        /// </summary>
        internal static string sskc {
            get {
                return ResourceManager.GetString("sskc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store_name 的本地化字符串。
        /// </summary>
        internal static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜寻 的本地化字符串。
        /// </summary>
        internal static string sx {
            get {
                return ResourceManager.GetString("sx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有 的本地化字符串。
        /// </summary>
        internal static string sy {
            get {
                return ResourceManager.GetString("sy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试作品粉碎审核通过列表 的本地化字符串。
        /// </summary>
        internal static string szpfcshtglb {
            get {
                return ResourceManager.GetString("szpfcshtglb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试作品粉碎列表 的本地化字符串。
        /// </summary>
        internal static string szpfslb {
            get {
                return ResourceManager.GetString("szpfslb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        internal static string tj {
            get {
                return ResourceManager.GetString("tj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string tj1 {
            get {
                return ResourceManager.GetString("tj1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加测试数据 的本地化字符串。
        /// </summary>
        internal static string tjcesj {
            get {
                return ResourceManager.GetString("tjcesj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加供应商 的本地化字符串。
        /// </summary>
        internal static string tjgys {
            get {
                return ResourceManager.GetString("tjgys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无库存 的本地化字符串。
        /// </summary>
        internal static string wkc {
            get {
                return ResourceManager.GetString("wkc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料采购 的本地化字符串。
        /// </summary>
        internal static string wlcg {
            get {
                return ResourceManager.GetString("wlcg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料属性 的本地化字符串。
        /// </summary>
        internal static string wlsx {
            get {
                return ResourceManager.GetString("wlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料预测 的本地化字符串。
        /// </summary>
        internal static string wlyc {
            get {
                return ResourceManager.GetString("wlyc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string xg {
            get {
                return ResourceManager.GetString("xg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 型号 的本地化字符串。
        /// </summary>
        internal static string xh {
            get {
                return ResourceManager.GetString("xh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X项 的本地化字符串。
        /// </summary>
        internal static string xitem {
            get {
                return ResourceManager.GetString("xitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 型检记录 的本地化字符串。
        /// </summary>
        internal static string xjju {
            get {
                return ResourceManager.GetString("xjju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统数量 的本地化字符串。
        /// </summary>
        internal static string xtsl {
            get {
                return ResourceManager.GetString("xtsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        internal static string xx {
            get {
                return ResourceManager.GetString("xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string xz {
            get {
                return ResourceManager.GetString("xz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string xz1 {
            get {
                return ResourceManager.GetString("xz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择文件 的本地化字符串。
        /// </summary>
        internal static string xzwj {
            get {
                return ResourceManager.GetString("xzwj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有 的本地化字符串。
        /// </summary>
        internal static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览 的本地化字符串。
        /// </summary>
        internal static string yl {
            get {
                return ResourceManager.GetString("yl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原料编号 的本地化字符串。
        /// </summary>
        internal static string ylbh {
            get {
                return ResourceManager.GetString("ylbh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        internal static string ys {
            get {
                return ResourceManager.GetString("ys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        internal static string ys1 {
            get {
                return ResourceManager.GetString("ys1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已删除 的本地化字符串。
        /// </summary>
        internal static string ysc {
            get {
                return ResourceManager.GetString("ysc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按原色料计算 的本地化字符串。
        /// </summary>
        internal static string ysl {
            get {
                return ResourceManager.GetString("ysl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string yx {
            get {
                return ResourceManager.GetString("yx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行类别 的本地化字符串。
        /// </summary>
        internal static string yxlb {
            get {
                return ResourceManager.GetString("yxlb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因 的本地化字符串。
        /// </summary>
        internal static string yy {
            get {
                return ResourceManager.GetString("yy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证可用性 的本地化字符串。
        /// </summary>
        internal static string yzkgx {
            get {
                return ResourceManager.GetString("yzkgx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制单人 的本地化字符串。
        /// </summary>
        internal static string zdr {
            get {
                return ResourceManager.GetString("zdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指导书 的本地化字符串。
        /// </summary>
        internal static string zds {
            get {
                return ResourceManager.GetString("zds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加 的本地化字符串。
        /// </summary>
        internal static string zj {
            get {
                return ResourceManager.GetString("zj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加行 的本地化字符串。
        /// </summary>
        internal static string zjh {
            get {
                return ResourceManager.GetString("zjh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加列 的本地化字符串。
        /// </summary>
        internal static string zjl {
            get {
                return ResourceManager.GetString("zjl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组立 的本地化字符串。
        /// </summary>
        internal static string zl {
            get {
                return ResourceManager.GetString("zl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周期 的本地化字符串。
        /// </summary>
        internal static string zq {
            get {
                return ResourceManager.GetString("zq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意事项 的本地化字符串。
        /// </summary>
        internal static string zysx {
            get {
                return ResourceManager.GetString("zysx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专用治具 的本地化字符串。
        /// </summary>
        internal static string zyzj {
            get {
                return ResourceManager.GetString("zyzj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string zz {
            get {
                return ResourceManager.GetString("zz", resourceCulture);
            }
        }
    }
}
